### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by seamus-brady** [ccrock4t/NARS-Python#3]
Hi

This is a very interesting project but there is no license specified.
Could you please add one or perhaps let me know what you allow?
The most developer friendly license is MIT (see https://github.com/opennars/OpenNARS-for-Applications for a similar project with this license)

Thanks!

Seamus

**Comment by ccrock4t** [comment]
Hello, good idea. After doing some reading, this MIT license seems the most reasonable choice for open-source software.

Anyone can use this code without restriction. It is based directly on the description of NARS in the book _Non-Axiomatic Logic - A Model of Intelligent Reasoning_ by Dr. Pei Wang.
